---
on: [push]
jobs:
  build-container:
    runs-on: docker
    container:
      image: vel.heimsbakk.no/containers/debian-bookworm:latest

    env:
      STORAGE_DRIVER: vfs
      BUILDAH_FORMAT: docker
      BUILDAH_ISOLATION: chroot
       
    steps:
      - run: echo $BUILDAH_ISOLATION
      - run: ls -la

      - name: Check out repository
        uses: https://vel.heimsbakk.no/actions/checkout@v4

      - name: Build container
        uses: https://vel.heimsbakk.no/actions/buildah-build@v2
        with:
          image: my-image
          tags: latest
          containerfiles: |
            ./Containerfile

      - run: ls -la
