---
on: [push]
jobs:
  build-container:
    runs-on: docker
    container:
      image: vel.heimsbakk.no/containers/debian-bookworm:latest

    env:
      STORAGE_DRIVER: vfs
      BUILDAH_FORMAT: docker
      BUILDAH_ISOLATION: chroot
       
    steps:
      - name: Get container registry path
        run: | 
          REGISTRY_PATH=${{ github.server_url }}
          REGISTRY_PATH=$(echo ${REGISTRY_PATH} | sed "s#https://##g")/containers
          echo REGISTRY_PATH=${REGISTRY_PATH} >> $GITHUB_ENV

      - name: Get repository name
        run: | 
          REPO_NAME=${{ github.repository }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=$(echo ${REPO_NAME} | sed "s#${REPO_OWNER}/##g")
          echo REPO_NAME=${REPO_NAME} >> $GITHUB_ENV
          echo ${REPO_NAME}

      - name: Check out repository
        uses: https://vel.heimsbakk.no/actions/checkout@v4

      - name: Build container
        id: build-container
        uses: https://vel.heimsbakk.no/actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Push Container
        id: push-container
        uses: https://vel.heimsbakk.no/actions/push-to-registry@v2
        with:
          image: ${{ steps.build-container.outputs.image }}
          tags: ${{ steps.build-container.outputs.tags }}
          registry: ${{ env.REGISTRY_PATH }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}          

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-container.outputs.registry-paths }}"
