---
on:
  push:
    paths:
      - '.forgejo/**/*.yaml'
      - '.forgejo/**/*.yml'
      - 'Containerfile'
      - 'Dockerfile'
  workflow_dispatch:
  schedule:
  - cron: '0 23 * * 2'

jobs:
  build-container:
    runs-on: shell

    # strategy:
    #   matrix:
    #     container:
    #       - extra_args: --build-arg=DEBIAN_RELEASE="bookworm"
    #         tags: latest bookworm ${{ github.sha }}
    #         platform: linux/amd64
    #         containerfile: Containerfile
    #       - extra_args: --build-arg=DEBIAN_RELEASE="trixie"
    #         tags: bookworm latest
    #         platform: linux/amd64
    #         containerfile: Containerfile


    steps:
      - name: Get container registry path
        run: |
          REGISTRY_PATH=${{ env.GITHUB_SERVER_URL }}
          REGISTRY_PATH=$(echo ${REGISTRY_PATH} | sed "s#https://##g")/${{ github.repository_owner }}
          echo REGISTRY_PATH=${REGISTRY_PATH} >> $GITHUB_ENV

      - name: Get repository name
        run: | 
          IMAGE_NAME=${{ github.repository }}
          REPO_OWNER=${{ github.repository_owner }}
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#${REPO_OWNER}/##g")
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#container-##g")
          echo IMAGE_NAME=${IMAGE_NAME} >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: vel.heimsbakk.no
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}
          provenance: false
          platforms: linux/amd64
          tags: vel.heimsbakk.no/containers/runner-debian:latest
          file: Containerfile
