---
on:
  push:
    paths:
      - '.forgejo/**/*.yaml'
      - '.forgejo/**/*.yml'
      - 'Containerfile'
      - 'Dockerfile'
  workflow_dispatch:
  schedule:
  - cron: '0 23 * * *'

jobs:
  build-container:
    runs-on: docker

    strategy:
      matrix:
        container:
          - build-args: |
              RELEASE=bookworm
            tags: |
              ${{ secrets.REGISTRY_NAME }}/${{ github.repository_owner }}/runner-debian:latest
              ${{ secrets.REGISTRY_NAME }}/${{ github.repository_owner }}/runner-debian:bookworm
            platforms: linux/amd64,linux/arm64
            containerfile: Containerfile
          - build-args: |
              RELEASE=trixie
            tags: |
              ${{ secrets.REGISTRY_NAME }}/${{ github.repository_owner }}/runner-debian:trixie
            platforms: linux/amd64,linux/arm64
            containerfile: Containerfile

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}
          provenance: false
          platforms: ${{ matrix.container.platforms }}
          tags: ${{ matrix.container.tags }}
          file: ${{ matrix.container.containerfile }}
          build-args: ${{ matrix.container.build-args }}
