---
on:
  push:
    paths:
      - '.github/**/*.yaml'
      - '.gitihub/**/*.yml'
      - 'Containerfile'
      - 'Dockerfile'
  workflow_dispatch:
  schedule:
  - cron: '0 23 * * 2'

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - extra_args: --build-arg=DEBIAN_RELEASE="bookworm"
            tags: latest bookworm ${{ github.sha }}
            platform: linux/amd64
            containerfile: Containerfile
          - extra_args: --build-arg=DEBIAN_RELEASE="trixie"
            tags: bookworm latest
            platform: linux/amd64
            containerfile: Containerfile

    env:
      STORAGE_DRIVER: vfs
      BUILDAH_FORMAT: docker
      BUILDAH_ISOLATION: chroot

    steps:
      - name: Get container registry path
        run: |
          REGISTRY_PATH="ghcr.io"
          REGISTRY_PATH=$(echo ${REGISTRY_PATH} | sed "s#https://##g")/${{ github.repository_owner }}
          echo REGISTRY_PATH=${REGISTRY_PATH} >> $GITHUB_ENV

      - name: Get repository name
        run: | 
          IMAGE_NAME=ghcr.io
          REPO_OWNER=${{ github.repository_owner }}
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#${REPO_OWNER}/##g")
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#container-##g")
          echo IMAGE_NAME=${IMAGE_NAME} >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}
          file: Containerfile